### ISSUE TITLE
API Response Error

### ISSUE THREAD

**Issue by NSTA1** [A9T9/Free-OCR-API-CSharp#1]
I get this error regardless of image chosen - subsequent to this call:

HttpResponseMessage response = await httpClient.PostAsync("https://api.ocr.space/Parse/Image", form);

![error](https://cloud.githubusercontent.com/assets/12947022/13673823/ad59c29a-e6d2-11e5-849d-c3b66080ce9e.jpg)

**Comment by A9T9** [comment]
Can you please try again?

I heard there have been some more reports about connection issues this
morning. So it seems there was a temporary issue with the system that fixed
itself. We will investigate. All works fine now.

**Comment by NSTA1** [comment]
Yes, working now.

**Comment by NSTA1** [comment]
You might want to make your demo a bit clearer when the problem is with the service:  "A task was cancelled" left me confused and wondering if I was doing something wrong :)

**Comment by NSTA1** [comment]
This is happening again....
